### ISSUE TITLE
Eliminate high-level wrappers

### ISSUE THREAD

**Issue by IvanUkhov** [stainless-steel/blas#10]
I started updating the package to use the Fortran bindings instead of the C ones, and now I tend to think that what we have right now in the root of the package should not be there. I think that the `metal` module should move to the root so that this package contains only minimalistic Rusty wrappers for BLAS. That code in the root is somewhat application specific; I, for example, have different requirements for storing and treating matrices and vectors. It started to deviate from BLAS. Moreover, the current root is in a deep work-in-progress state right now, and potential users just get confused; bare `metal` is sufficient in most cases.

@cmr, what do you think if I move `metal` to the root, and high-level wrappers will eventually become a separate package? Thanks!

Regards,
Ivan

**Comment by cmr** [comment]
Sounds good! I agree that I had a difficult time using the high-level code (let alone trying to write it to be more useful).
