### ISSUE TITLE
link failure on Windows during cargo build

### ISSUE THREAD

**Issue by scharris** [stainless-steel/blas#17]
With a 64 bit mingw toolchain, attempt to build on Windows 10 is failing at link stage.  The first signs of trouble in the output are messages such as:
 
    ld.exe: i386 architecture of input file `../libopenblas_haswellp-r0.2.17.a(saxpy.obj)' is incompatible with i386:x86-64 output
(This is repeated for many many object files).

This same toolchain is able to successfully compile and link the latest openblas distribution obtained independently.

The toml contains:
    blas = "0.*
and the command was:
    cargo build

A shortened version of the output can be seen [here](https://gist.github.com/scharris/fd07851fa410940889145d93063f95f9) .

(Until this is resolved, is there a way to have the blas crate use the openblas artifacts I was able to compile myself independently?)

**Comment by IvanUkhov** [comment]
Thanks for the issue! As a workaround, disable the default feature of the crate and link to your OpenBLAS using a build script.

**Comment by IvanUkhov** [comment]
If you manage to make it work on Windows, please share your solution, and pull requests are always very welcome. It’s probably something that should be fixed in `openblas-provider`, not in `blas` or `blas-sys`.

**Comment by scharris** [comment]
Update - I was wrong, I can't compile the original openblas installation on its own after all, when passing the same params to make as the build.rs does.  Not sure what's going on presently, I'm trying to replicate on another machine, will update when I know more.  This maybe an issue with openblas or my setup.

**Comment by IvanUkhov** [comment]
I suspect that the compilation steps in `openblas-provider` should be changed to reflect the instructions given [here](https://github.com/xianyi/OpenBLAS/wiki/How-to-use-OpenBLAS-in-Microsoft-Visual-Studio) for Windows.

**Comment by scharris** [comment]
I couldn't get any of the various mingw-w64 distributions to work for me, that ecosystem seems to be a mess right now and the openblas docs seem to be a bit out of date for Windows installation.  Using the 64 bit mingw-w64 from the page you linked, I got a distribution without fortran or make (make is renamed to a hyphenated name), and some other things would also probably be missing (e.g. perl is needed by openblas build process).  I tried some guy's personal build recommended on another openblas page also, which did include those tools, but got the linker error mentioned above.

Anyway, good news is that a full MSys2 install (plus a pacman call to install some dev tools) will build the openblas distribution.  The only problem is that it won't install properly as called from build.rs in openblas-provider, because of what looks like a simple escaping issue in that final step:

    C:UsersSharrisProgrammingprojectssdar-Rnativetargetdebugbuildopenblas-provider-622ec21a2729752eout/opt/OpenBLAS/include/openblas_config.h: No such file or directory

Note that the backslashes in the windows path seem to have been removed, I guess they were interpreted as escapes in the string literal.

BTW: Here is a complete setup that will get a Windows machine through the compile and linking (just not the install as called from openblas-provider) of openblas:

    #Install Msys2 (64 bit) from http://msys2.github.io/, then in msys2 shell:
    pacman -S perl make gcc gcc-fortran

Then "make USE_THREAD=0 YES_CBLAS=1 -j8 libs netlib shared" should work in the openblas source distribution directory (tested on Windows 7 and 10).

If it's OK with you I'll look at getting the install command fixed in build.rs and create a pull request for the change.

**Comment by IvanUkhov** [comment]
Thanks a lot for the investigation! To be honest, I didn’t have Windows even remotely in mind when I wrote that build script. If it’s only about Windows’ backslashes, the problem should be relatively easy to fix. Apart from `DESTDIR`, Cargo’s [`cargo:rustc-link-search`](https://github.com/cmr/openblas-provider/blob/master/build.rs#L42) needs probably extra care too.

Please feel free to open a pull request. It’d be also nice if we could get it work on AppVeyor.

**Comment by IvanUkhov** [comment]
I’ve push a dummy AppVeyor configuration file to `openblas-provider`. If you know what and how should be installed to make OpenBLAS compile, please feel free to modify that file too.

**Comment by scharris** [comment]
Changes are very minor and are working on Windows 7 and 10 test machines.  I will test on Linux tomorrow and then make the pull request.  I'm not familiar with AppVeyor yet but I'll look into it, I might try that later in the week.

[build.rs diff](https://github.com/scharris/openblas-provider/commit/e281c8)

**Comment by IvanUkhov** [comment]
I close this in favor of [that](https://github.com/cmr/openblas-provider/issues/10).
