### ISSUE TITLE
safety - check slice sizes against size params

### ISSUE THREAD

**Issue by scharris** [stainless-steel/blas#18]
Currently if the user specifies invalid size parameters to blas routines, buffer overruns of the input slices may result within the foreign blas code.

It would be easy to check passed size arguments against slice sizes in many if not all of the wrapper blas functions prior to the foreign call. The performance cost should be negligible, much less than having even one additional row in an input matrix.

The checks would be only that the input buffer bounds are not overrun, it would not be a requirement that input sizes (or products of two of them) exactly match slice lengths, so full flexibility of the blas routines would be maintained.

**Comment by IvanUkhov** [comment]
Yes, sanity checks would certainly be nice to have. The biggest challenge, as I see it, is that it will involve a lot of manual work, which will be tedious and error-prone. One has to go through all the functions one by one, read the corresponding documentation, figure out the meaning of each parameter, and then insert adequate checks. Currently the content of the `blas` and `lapack` crates are generated by Python scrips based on the content of `blas-sys` and `lapack-sys`, respectively.

**Comment by IvanUkhov** [comment]
If you know an automated way of doing this, please share. Thank you.

**Comment by scharris** [comment]
Yeah it is a lot of tedious work for sure. I'll try to do some and see how long it would take or if there's a pattern I can automate.  At least there's a lot of obvious repetitions of functions to take advantage of (s/d/z... functions etc).

But do you expect them to ever need to be auto-generated again in total?  In other words if a new spec came out, would to regenerate totally, or maybe just automate generating the new functions?  I would expect that most of the longstanding functions wouldn't change their signatures (so wrapper wouldn't change either) and so wouldn't need regenerating, but I don't really know...
