### ISSUE TITLE
Confusion regarding 0 and 1 based indexing

### ISSUE THREAD

**Issue by dthul** [stainless-steel/blas#24]
Not sure if this is the right place for this issue. I am using this crate in its latest version and link against a self-built OpenBLAS 0.2.19.

Consider the following piece of code:
```rust
use blas::c as cblas;
use blas::fortran as fblas;

#[test]
fn test_amax() {
    let idx_c = cblas::isamax(1, &[1.0], 1);
    let idx_f = fblas::isamax(1, &[1.0], 1) as i32;
    assert_eq!(idx_c, idx_f); // idx_x = 0 while idx_f = 1
}
```

The assertion will fail since `idx_c` and `idx_f` are not the same. It looks like the Fortran version returns 0 as an error value and 1-based indices while the C version returns 0 as an error value and 0-based indices (meaning than one can't differentiate between an error and a successful return value).
The documentation (OpenBLAS refers to the Intel MKL docs as a valid reference) is quite clear on the fact that the index should be 1-based though:

> Returns the position of vector element that has the largest absolute value such that x[index-1] has the largest absolute value.
> -- https://software.intel.com/en-us/mkl-developer-reference-c-cblas-i-amax

**Comment by IvanUkhov** [comment]
Thanks for the issue! I think it has to do with [the fact](https://en.wikipedia.org/wiki/Comparison_of_programming_languages_%28array%29#Array_system_cross-reference_list) that C features zero-based indexing while Fortran features one-based indexing. So the output is correct: that first element in the array has index 0 from C’s standpoint and 1 from Fortran’s.

This crate provides thin wrappers around the underlying C and Fortran functions without modifying anything on the way. I agree that it’s confusing, but it is what it is unfortunately.
