### ISSUE TITLE
blas and openblas-sys link against different versions of gfortran

### ISSUE THREAD

**Issue by shradej1** [stainless-steel/blas#28]
Attempting to build blas on OSX High Sierra.
gcc 7 and 6 installed via homebrew.

If brew has 7 symlinked in, openblas-sys links correctly against gcc/7/libgfortran.4.dylib, but blas links against a non-existent gcc/6/libgfortran.3.dylib.  I can't figure out where this is coming from.

If brew has gcc 6 symlinked in, things work as expected.

## How to reproduce:
1. checkout blas
1. brew install gcc gcc6
1. brew switch gcc 7.X.X
1. cargo clean 
1. cargo bench

## Observed Behavior
`dyld: Library not loaded: /usr/local/opt/gcc/lib/gcc/6/libgfortran.3.dylib`

`otool -L target/release/deps/blas-25ccd25572093ac2` shows that blas has linked against `/usr/local/opt/gcc/lib/gcc/6/libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)`.  I don't know where this path is coming from.  This image does not exist.

`otool -L target/release/build/openblas-src-93b86530c5caba86/out/opt/OpenBLAS/lib/libopenblas_haswellp-r0.2.20.dylib` shows that openblas has correctly linked against `/usr/local/opt/gcc/lib/gcc/7/libgfortran.4.dylib`.

## Workaround
1. brew switch gcc 6.X.X
1. cargo clean
1. cargo bench

In this case, both dylibs link against the gcc-6 libgfortran.3.dylib.

**Comment by IvanUkhov** [comment]
Thanks for the issue! I haven’t tried it with two versions of GCC, but one guess is that there is an outdated symlink in your `.rustup` or alike. Check if you have any mentioning of `gfortran` there.

```bash
find ~/.rustup/ -iname '*fortran*'
```

**Comment by shradej1** [comment]
There sure is.  I suppose this is maybe a rustup issue then - or maybe not an issue at all.  I'll verify that reinstalling rustup with gcc 7 symlinked in resolves the issue later tonight.  Thanks!

**Comment by shradej1** [comment]
`rustup uninstall nightly`
`rustup install nightly`

removed the broken symlink in ~/.rustup.  But now linking completely fails with 

`error: linking with `cc` failed: exit code: 1
...
note: ld: library not found for -lgfortran`

The openblas dylib still links correctly against libgfortran.

**Comment by IvanUkhov** [comment]
Please reall the discussion [here](https://github.com/cmr/netlib-src/issues/7).

**Comment by shradej1** [comment]
Well that explains how that link got there in the first place :)

[The build.rs file in openblas-src](https://github.com/cmr/openblas-src/blob/master/build.rs) explicitly adds a `println!("cargo:rustc-link-lib=dylib=gfortran");`.  Is that necessary?  Removing it seemed to resolve the issues I was seeing, without me having to create a link in ~/.rustup.  The libopenblas.dylib built by the Makefile is correctly linked to gfortran.

**Comment by IvanUkhov** [comment]
Thanks! I’ll try to look into this.

For purposes of organization, I close this one in favor of [that one](https://github.com/stainless-steel/blas/issues/28).
