### ISSUE TITLE
Add thorough test suite

### ISSUE THREAD

**Issue by cmr** [stainless-steel/blas#5]
Port over the BLAS test suite.

**Comment by cmr** [comment]
Turns out porting Fortran to Rust is *really* boring and annoying. I'm adding some quickcheck-based tests instead, for now. I've already added most of the level 1 real tests. And found some bugs in OpenBLAS...

**Comment by IvanUkhov** [comment]
That last part sounds especially interesting) For clarify, I’ve moved the tests from `src` to `tests` as there will probably be a plenty of them.

**Comment by IvanUkhov** [comment]
I close this as the package is a merely a wrapper.
